### ISSUE TITLE
TypeError: state.get is not a function

### ISSUE THREAD

**Issue by billgo** [hendrathings/react-boilerplate-redux-persist-sample#1]
Do you have this problem

**Comment by martin-kieliszek** [comment]
I have this problem too.

**Comment by martin-kieliszek** [comment]
Perhaps @hendrathings isn't getting these issues because he has modified his app render function to not depend on anything within the boiler plate ie. No LanguageProvider dependency (where the state.get error is occuring).

Perhaps if you put this back into app.js you may see the same error @hendrathings 
```js
const render = (messages) => {
  ReactDOM.render(
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <LanguageProvider messages={messages}>
          <ConnectedRouter history={history}>
            <App />
          </ConnectedRouter>
        </LanguageProvider>
      </PersistGate>
    </Provider>,
    MOUNT_NODE
  );
};
```

Error:

`selectors.js?cf0a:6 Uncaught (in promise) TypeError: state.get is not a function`

Which maps to this line (6) in App/LanguageProvider/selectors.js
```js
const selectLanguage = (state) => state.get('language');
```
The languageProviderReducer is being combined into the store so you would hope that it is capable of obtaining the current state, however it does not.

Thoughts?

**Comment by sincerekamal** [comment]
@martin-kieliszek did you fix this issue later ? any solution to integrate **`redux-persist`** in **`react-boilerplate`** ?

**Comment by saishav7** [comment]
Facing the same issue, does anyone have a solution for this?

**Comment by atifaziz2** [comment]
I am facing this issue, anyone have a solution for this?

**Comment by atifaziz2** [comment]
@billgo can you please let me know the solution of this problem?

**Comment by billgo** [comment]
@atifaziz2 I just roll back to the previous version, `redux-persist: v4.10.2`.
